#!/bin/bash

SwitchAudioSource -s "MCHStreamer I2S TosLink"

if [ "$#" -ne 0 ]; then
   echo you passed "$#" arguments so I will open system preferences to show you the MOTUness

   # Open sound preferences so we can see the result
   osascript -e 'tell application "System Preferences" to activate'
   osascript -e 'tell application "System Preferences" to reveal anchor "input" of pane id "com.apple.preference.sound"'
fi
