#!/bin/bash
cd "$(dirname "$0")/.."
networksetup -setairportpower en0 off 2>/dev/null || true
trap 'networksetup -setairportpower en0 on 2>/dev/null || true' EXIT
exec chuck -c8 "client.ck:$1:pkmn:flash" --bufsize:1024
