#!/bin/bash
cd /Users/slork/slork/users/tae1han/ds9-bing
MIDI_DEV="USB Midi Cable"
for arg in "$@"; do [[ "$arg" != [0-9]* ]] && MIDI_DEV="$arg"; done
chuck autonomousFeeder.ck >/dev/null 2>&1 &
exec chuck "server.ck:${MIDI_DEV}:sim:pad"
